import { ISidebarNavTab } from "../interfaces/sidebar-nav-tab.interface";
export const sidebarNavTabsConst: ISidebarNavTab[] = [
  {
    name: 'board',
    label: 'Панель',
    icon: 'dashboard',
    type: 'link',
    url: '/board',
    disabled: false,
  },
  {
    name: 'orders',
    label: 'Заказы',
    icon: 'description',
    type: 'link',
    url: '/orders',
    disabled: false,
  },
  {
    name: 'tasks',
    label: 'Задачи',
    icon: 'task',
    type: 'link',
    url: '/tasks',
    disabled: false,
  },
  {
    name: 'finance',
    label: 'Финансы',
    icon: 'finance',
    type: 'link',
    url: '/finance',
    disabled: false,
  },
  {
    name: 'documents',
    label: 'Документы',
    icon: 'folder_open',
    type: 'link',
    url: '/documents',
    disabled: false,
  },
  {
    name: 'logistics-map',
    label: 'Карта логистики',
    icon: 'explore',
    type: 'link',
    url: 'tools/logistics-map',
    disabled: false,
  },
  {
    name: 'tracking',
    label: 'Отслеживание',
    icon: 'location_on',
    type: 'link',
    url: 'tools/tracking',
    disabled: false,
  },
  {
    name: 'route-planner',
    label: 'Планировщик маршрутов',
    icon: 'route',
    type: 'link',
    url: 'tools/route-planner',
    disabled: false,
  },
  {
    name: 'bookings',
    label: 'Bookings',
    icon: 'insert_drive_file',
    type: 'link',
    url: 'bookings',
    disabled: false,
  }
];
